### ISSUE TITLE
Mocha test returning 'ECONNREFUSED'

### ISSUE THREAD

**Issue by mattlemmone** [CEN3031-spr16/UF-Directory-App-Assignment#1]
I have manually tested my server.js file via console output to make sure it returns the correct outputs and statuses. Everything looks good.

When I use mocha to test, I receive the following:

`λ mocha server.test.js`

```
UF Directory Server Unit Tests
    Server responds to requests
      1) should respond
    Server provides listing data as JSON on proper request
      2) responds correctly to a GET request to "/listings"
      3) responds with a 404 error to other GET requests


  0 passing (3s)
  3 failing

  1) UF Directory Server Unit Tests Server responds to requests should respond:
     Uncaught AssertionError: expected Error {
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  message: 'connect ECONNREFUSED'
} to not exist
      at Request._callback (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\server.test.js:44:20)
      at self.callback (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\node_modules\request\request.js:198:22)
      at Request.onRequestError (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\node_modules\request\request.js:820:8)
      at Socket.socketErrorListener (_http_client.js:271:9)
      at net.js:459:14

  2) UF Directory Server Unit Tests Server provides listing data as JSON on proper request responds correctly to a GET request to "/listings":
     Uncaught AssertionError: expected Error {
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  message: 'connect ECONNREFUSED'
} to not exist
      at Request._callback (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\server.test.js:54:20)
      at self.callback (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\node_modules\request\request.js:198:22)
      at Request.onRequestError (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\node_modules\request\request.js:820:8)
      at Socket.socketErrorListener (_http_client.js:271:9)
      at net.js:459:14

  3) UF Directory Server Unit Tests Server provides listing data as JSON on proper request responds with a 404 error to other GET requests:
     Uncaught TypeError: Cannot read property 'statusCode' of undefined
      at Request._callback (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\server.test.js:65:17)
      at self.callback (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\node_modules\request\request.js:198:22)
      at Request.onRequestError (C:\Users\Matt\Documents\GitHub\UF-Directory-App-Assignment\node_modules\request\request.js:820:8)
      at Socket.socketErrorListener (_http_client.js:271:9)
      at net.js:459:14
```

The first and second error are due to some connection issue it seems, so it cant check for the status in the responses. The third error is probably similar - because it isn't receiving a response, it cannot check for the statusCode property.

I am using Node v0.12.2 and npm v2.7.4.

**Comment by irwincollin** [comment]
Are you sure the server is being created and starting listening properly? Print statements can help debug this.

Secondly, are you sure the server is running while you run the test? 

For example I opened two shells and ran 'node server.js' in one and then 'mocha server.test.js' in the other. 

Also make sure you can get to 127.0.0.1:8080/listings or just 127.0.0.1:808, while the server is running, in your web browser.

**Comment by mattlemmone** [comment]
Ah. I was under the impression that the test file would run the server for some reason. Solved by running both the test and server concurrently. Thanks.

**Comment by akashjain12366** [comment]
@mattlemmone it would be a great help if you can share, how did you run test and server concurrently?
